### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by piranha** [r0man/sablono#111]
Hi! There is [a branch of rum](https://github.com/tonsky/rum/tree/server/), which makes it possible to render CLJS apps on JVM, without having to run React on Node.js or even React on Nashorn. This is done by writing application in `.cljc` files and generating simple function for Clojure (server-side) version, which returns hiccup-like data.

This data is then rendered by [rum.server-render](https://github.com/tonsky/rum/blob/server/src/rum/server_render.clj) namespace, which tries to replicate behavior of both React and Sablono - so that server-rendered parts are identical to what application will generate then on client-side.

So far this works quite well, except for the part where I have to check my app all the time and fix small issues bit by bit. :)

I've been thinking about that somewhat, and a question arises - what do you think about making a server-side version of sablono? Which will generate html strings instead of calls to `js/React.createElement`?

I've looked briefly at sablono's code, and I'm not exactly sure how to proceed - or this would be a pull request, and not an issue. :) So I guess I'm looking for help, either in form of directions or maybe direct changes in sablono so that I can use it instead of my clunky `rum.server-render` stuff. :)

**Comment by r0man** [comment]
Hey @piranha,

I haven't thought about server side rendering too much myself. I
think it would be nice if sablono would support this, but also
think the devil is in the detail..

I know that @arohner was/is looking into this as well. He has a
library called foam that does this for om applications. Maybe
it's worth to take a look at his approach.

I don't have time to work on this myself at the moment, but would
support any efforts to make this happen.

Roman

**Comment by piranha** [comment]
I've been to his talk at Clojure/Conj, where he presented his approach and what I did was obviously inspired by his library. In his case though he's not using sablono, he's doing everything through `om.dom` calls (and their equivalent on the server).

In my case, Rum's API obviously assumes sablono, so having sablono render to string by itself would be pretty cool.

I'll try to dive in then, and will get back if any question arises. :)

**Comment by arohner** [comment]
I use sablono for my own CLJS projects, so foam already has most of an implementation of server-side sablono: https://github.com/arohner/foam/blob/master/src/foam/html.clj

I haven't officially announced it because 1) There are likely still some differences between foam.html and 'real' sablono and 2) if I do announce it, I'll very likely split it into a separate project from foam first. 

I don't have time atm to work on it, but if the code is interesting, have at it :-)

**Comment by altV** [comment]
@arohner, can I ask on type safety in hiccup reimplementation?
unfortunately, current hiccup is not typesafe at all -  (hiccup.page/html5 [:html [:body "Hi!</html>"]]) will not escape tags :(

There's a 2.0 branch of hiccup, but it's not completed

**Comment by piranha** [comment]
@altV when you try to implement hiccup-like syntax for react, you have to escape all content (except `dangerouslySetInnerHTML`, of course), so this is less of a problem than with normal hiccup.

**Comment by arohner** [comment]
@r0man: @JoelSanchez made an excellent PR to foam, to get data-reactid working, so react will re-use the server-side rendered html, without forcing a new layout. I found an issue in my own code where foam's html emits HTML attributes in a different order than sablono, which causes react to complain and ignore the server-side html.

To get the rendered output consistent, would you take a patch that sorts attribute names, so we can make them always consistent?

**Comment by arohner** [comment]
@piranha on the broader question of SSR, I'm not sure there is a react-wrapper-agnostic solution. foam explicitly supports Om only, and I'm not sure how to make it Om agnostic. 

I guess maybe there could be a well-named protocol for rendering react that is shared across projects, but that sounds cumbersome.

**Comment by r0man** [comment]
@arohner Sure. I would love to support server side rendering. I think this sorting would need to be done in the compiler and the interpreter. Would you also add some tests so we don't mess things up in the future ;)

**Comment by r0man** [comment]
Delegating to the om.next server sider renderer for a while now ...
https://github.com/r0man/sablono/commit/fd57b4edcffd496e0044f13576e730ad1d4e091e
