### ISSUE TITLE
Not support html `contenteditable` attribute

### ISSUE THREAD

**Issue by gfZeng** [r0man/sablono#112]
the rendered element has no `contenteditable` attribute
```clojure
[:td {:contenteditable "true"} "my desc"]
```

**Comment by nha** [comment]
Did you try  `[:td {:contentEditable "true"} "my desc"]` ?

**Comment by gfZeng** [comment]
@nha 
It's ok, thanks for your suggestion
`[:td {:contentEditable "true"} "my desc"]`
