### ISSUE TITLE
Unsupported style property

### ISSUE THREAD

**Issue by rhacker** [r0man/sablono#113]
I'm not sure if this is the right place to post. But I get some warnings regarding inline styling with sablono, should we convert the clojure naming style to javascript naming style regarding styling. For example : 
```
:border-bottom -> :borderBottom
:z-index -> :zIndex
```

I have some warnings because of this. It's an easy fix but I'm curious about this.

Thanks for creating this lib :)

**Comment by r0man** [comment]
@rhacker Sorry, I don’t quite follow you. Style attributes should be converted to camel case. If not, then you hit a bug. Could you provide more details, ideally a test case that triggers such a warning?

**Comment by rhacker** [comment]
@r0man thanks for your response. I will try to find a minimal case and send it here.

**Comment by rhacker** [comment]
Sorry for slow response, it doesn't have any problem. Thanks for participating.
