### ISSUE TITLE
Inserting Custom Tags (a la WebComponents)

### ISSUE THREAD

**Issue by twashing** [r0man/sablono#122]
Can we insert custom tags using Sablono (ex: `<div>Hello <my-tag>World</my-tag></div>`)? I'm in the market for using webcomponents, and react certainly allows it (see [here](https://facebook.github.io/react/docs/webcomponents.html)).

I ask because it looks like Om Next still employs whitelisting (see [here](https://github.com/omcljs/om/blob/master/src/main/om/dom.clj#L4)), which React doesn't do anymore (at least [from JSX](https://facebook.github.io/react/docs/tags-and-attributes.html)).

**Comment by r0man** [comment]
@twashing Yes, this is possible for quite some time now. I used Sablono successfully with Polymer. However, you still might run into issues because custom attributes are still not supported by React.

**Comment by twashing** [comment]
@r0man Nice. I'm playing around with it right now. I'll get back to you with any questions. Thanks!!
