### ISSUE TITLE
CHANGELOG.org is a little bit outdated

### ISSUE THREAD

**Issue by piranha** [r0man/sablono#136]
It only contains information about 0.7.3. :)

**Comment by r0man** [comment]
@piranha I feel like removing the changelog, but here you go :)

https://github.com/r0man/sablono/blob/c37fe4232f7a89ddb8038a0197ee4c7febfef9f5/CHANGELOG.org

**Comment by piranha** [comment]
Why removing? Reading changelog is much easier than reading git logs :-)
