### ISSUE TITLE
^:inline does not work on 2nd element

### ISSUE THREAD

**Issue by chpill** [r0man/sablono#141]
Hello~ First thanks a lot for sablono, it is an awesome library.

I have tried to use the `^:inline` metadata to get read of the `interpret` calls in the code emitted by sablono. It seems that it does not work in all cases though. I have made a [dummy project] to illustrate the issue, but here is the gist of it:

[dummy project]: https://github.com/chpill/sablono-bug

```
(ns sablono-bug.core
  (:require [sablono.core :as sablono]))

(defn my-react-component
  "Dummy function that returns a react component"
  []
  (sablono/html [:span "plop"]))

(def a
  "Here, inlining works just fine"
  (sablono/html [:div
                 {}
                 ^:inline (my-react-component)]))

(def b
  "Here it does not work"
  (sablono/html [:div
                 ^:inline (my-react-component)]))
```

Case `a` compiles to the following js:

```
sablono_bug.core.a = React.createElement("div",null,sablono_bug.core.my_react_component.call(null));
```

Case `b` compiles to the following js (indented for clarity):

```
sablono_bug.core.b = (function (){
  var attrs8164 = sablono_bug.core.my_react_component.call(null);
  return cljs.core.apply.call(
    null,
    React.createElement,
    "div",
    ((cljs.core.map_QMARK_.call(null,attrs8164)) ?
      sablono.interpreter.attributes.call(null,attrs8164):null),
      ((cljs.core.map_QMARK_.call(null,attrs8164)) ?
        null :
        new cljs.core.PersistentVector(
          null,
          1,
          5,
          cljs.core.PersistentVector.EMPTY_NODE, [sablono.interpreter.interpret.call(null,attrs8164)], null)));
})();
```

I have not had the time to dive in the code yet, but maybe you have an idea why it does not work in case `b`?

**Comment by r0man** [comment]
@chpill Should be fixed in master. Can you try it out with `0.7.7-SNAPSHOT`.

**Comment by chpill** [comment]
I just tried it, works like a charm! No more `interpret` calls in my generated js. Thanks!
