### ISSUE TITLE
Regression: wrapped select doesn't render child elements properly

### ISSUE THREAD

**Issue by roman01la** [r0man/sablono#145]
@r0man I've just spent a half of the day debugging a problem which happened to be a regression after dbd9de74c6 commit 🙃

The problem is that wrapped select element renders previous set of child elements after every update when you toggle children for example. I think it goes somewhere into updating local state of the wrapper element from its props.

I've added `controlled-select` test here https://github.com/roman01la/sablono/tree/interpreter-regression so you can reproduce the bug.

Here I dropped a log into wrapper's `render` method to see the difference between component's props and state. The numbers are the length of `children` seq. It clearly shows that state and props are out of sync.
![screen shot 2017-01-11 at 6 41 12 pm](https://cloud.githubusercontent.com/assets/1355501/21857277/9331bbc8-d82d-11e6-9878-57070e43f203.png)

**Comment by r0man** [comment]
@roman01la Could you please try out this branch and let me know if this solves the issue? I added your card to the input tests, so you can try it out. Thanks!
https://github.com/r0man/sablono/pull/146

**Comment by roman01la** [comment]
@r0man Checked, works well now. Thanks!

**Comment by r0man** [comment]
@roman01la Cool. Just pushed `0.7.8-SNAPSHOT` to Clojars.
