### ISSUE TITLE
How to clear a HTML input element?

### ISSUE THREAD

**Issue by rdpfeiffer** [r0man/sablono#170]
I just started using Sablono, and it made generating some HTML browser functionality really quick and easy. I like it!

But I'm stuck on how to clear the text from an HTML input element. I know that it must be possible. What's the correct way to do this?

Thanks!

**Comment by r0man** [comment]
@rdpfeiffer For a controlled input set the value attribute to the empty string, for an uncontrolled input  you need a reference to the dom element and clear the text via the dom api. How to get a reference to the dom node depends on the React wrapper you are using. Om has the `dom/node` function, Rum has `ref-node` or `dom-node` to do this.

Also take a look at https://facebook.github.io/react/docs/refs-and-the-dom.html

**Comment by rdpfeiffer** [comment]
@r0man If I'm understanding you correctly, I think that this code snippet gives me the reference I need:
(js/document.getElementById "input-field")

The problem is that I can't figure out what to do next. I thought that I might be able to use sablono.interpreter/update-state, but I wasn't sure if that was the right thing to do or how to get it to work for me.

You mentioned Om and Rum. Right now I'm kinda experimenting with browser UI development using various technologies in ClojureScript. My current experiment is to see what I can do by just using Sablono alone. I've just about made what I want, but I'm stuck on this "clear input" issue.

**Comment by r0man** [comment]
@rdpfeiffer I think you want this:
```
(set! (.-value (js/document.getElementById "input-field")) "")
```

**Comment by rdpfeiffer** [comment]
@r0man Yes, exactly!

Thanks so much, it does just what I want! (I guess that I couldn't get my "functional programming mind" into finding the side-effecting "set!" function that I needed> :-) )
