### ISSUE TITLE
Are non-breaking spaces supported?

### ISSUE THREAD

**Issue by rdpfeiffer** [r0man/sablono#171]
I thought that the following code snippet would work:

`[:p "foo&nbsp;bar"]`

and produce:
> foo bar

But the `&nbsp;` doesn't get interpreted in my Sablono code. Is there a different/better way to do this? Thanks!

**Comment by r0man** [comment]
@rdpfeiffer I'm only aware of this:
```
[:p {:dangerouslySetInnerHTML {:__html "foo&nbsp;bar"}}]
```

**Comment by rdpfeiffer** [comment]
OK, thanks. I'm a bit leery of the "dangerously" part. :-)
