### ISSUE TITLE
:npm-deps compat

### ISSUE THREAD

**Issue by lgrapenthin** [r0man/sablono#176]
If I require per :npm-deps Compiler feater, is there already a way to use Sablono? Right now Sablono says No such namespace: cljsjs.react, could not locate cljsjs/react.cljs, cljsjs/react.cljc, or JavaScript source providing "cljsjs.react", in resources/public/cljs/out/sablono/interpreter.cljc

**Comment by r0man** [comment]
@lgrapenthin I haven't looked at the new :npm-deps stuff yet, and quite busy at the moment and don't have time to look into this now. @Deraen opened a PR recently but I'm not sure of it's state. 
https://github.com/r0man/sablono/pull/175

**Comment by Deraen** [comment]
I will try to fix the tests with the changes soon. Releasing the support will require updating also Om, Rum and Devcards at the same time as Sablono.

Btw. `:npm-deps` is not a correct name for the new features. "Node modules support" or "Module processing" are better names. I'll try to update ClojureScript docs before we update all the packages.

**Comment by r0man** [comment]
@Deraen ok, thanks for the update and the work on the PR.

**Comment by r0man** [comment]
Closing this. Latest master requires React now, instead of using js/React
