### ISSUE TITLE
Add support for more forms (e.g. `when`)

### ISSUE THREAD

**Issue by zlorf** [r0man/sablono#184]
The compiler "walks" properly on some forms, but not on others:
```
user=> (compile-html '(if 6 [:div.x.y {:href 6} "text"]))
(if 6 (js/React.createElement "div" #object[cljs.tagged_literals.JSValue 0x631a57c2 "cljs.tagged_literals.JSValue@631a57c2"] "text"))
user=> (compile-html '(when 6 [:div.x.y {:href 6} "text"]))
(sablono.interpreter/interpret (when 6 [:div.x.y {:href 6} "text"]))
```
I think that some popular forms are missing here. @rauhs has included a more comprehensive list:
https://github.com/rauhs/hicada/blob/master/src/hicada/compiler.clj#L159

Maybe we can move those multimethods, with the proper author attribution?

**Comment by r0man** [comment]
@zlorf Sure, PR with some tests welcome!

**Comment by rauhs** [comment]
No attribution required. I think some of them also came from others from a gist.

**Comment by r0man** [comment]
@zlorf Yes, you are right. I fix it over here: https://github.com/r0man/sablono/pull/185

**Comment by zlorf** [comment]
Excellent, thanks!

**Comment by r0man** [comment]
@zlorf I added a couple of more forms from @rauhs (thanks!) hicada's allgäu ;)

**Comment by zlorf** [comment]
@r0man Thanks!
I was considering to try refactor my approach to invoke clojurescript macro compiler (no time, though).
But, well, enumerating all forms is still a solution. :)
