### ISSUE TITLE
React warning

### ISSUE THREAD

**Issue by danielsz** [r0man/sablono#21]
React complains about missing "key" prop in the array, this happens only for dynamic children.

The exact message is: "Each child in an array should have a unique "key" prop. Check the render method of undefined. See http://fb.me/react-warning-keys for more information." 

``` clojure
(html [:div 
             [:h2 "Menu"]
             [:ul (for [component (om/build-all menu-item (:items data) {:init-state {:channel channel}})]
                    component)]])
```

Same with `build`

``` clojure
(html [:div 
             [:h2 "Menu"]
             [:ul (for [item (:items data)] 
                  (om/build menu-item item {:init-state {:channel channel}})]])
```

No such message when using default notation: 

``` clojure
(dom/div nil
               (dom/h2 nil "Menu")
               (apply dom/ul nil
                      (om/build-all menu-item (:items data) {:init-state {:channel channel}}))))))
```

**Comment by dustingetz** [comment]
Is there a reason why I can't set the key prop through sablono or maybe I am doing it wrong?

```clojure
[:tbody
            (map (fn [{:keys [id name]}]                   
                   [:tr {:key id}
                    [:td id]
                    [:td name]])
                 collection)]]
```

**Comment by wiseman** [comment]
I'm wondering the same thing as @dustingetz.

**Comment by didibus** [comment]
I think you need to use `:react-key` in case you want to add `:key` as an html attribute, so you need to disambiguate.

Also, Sablono renders sequences and lists as JS arrays, and that's when react will complain with this warning.
