### ISSUE TITLE
Compile warning about `number` when using `count`

### ISSUE THREAD

**Issue by lynaghk** [r0man/sablono#33]
I'm using sablono "0.2.16" with om "0.6.2" and clojurescript "0.0-2202".
Using plain cljs `count` within an html macro within an om render gives a compiler warning about undefined var `number`.
I'm not sure if this is a problem with Sablono or ClojureScript's compiler.
I cannot expand the macro within plain Clojure because trying to require Sablono returns a `cljs.tagged_literals.JSValue` class not found error.

Here's some code demonstrating the issue.
(Note that the code actually runs fine; the problem is just the unnecessary compiler warning)

```clj
(ns scratch
  (:require [om.core :as om :include-macros true]
            [sablono.core :as html :refer-macros [html]]))


(html [:div (count [1 2 3])])
;;Compiles fine, no warnings

(reify
  om/IRender
  (render [_]
    (html [:div (count [1 2 3])])))

;;Gives compile warning
;;WARNING: Use of undeclared Var scratch/number at line...
```

**Comment by brandonbloom** [comment]
We're affected too.

**Comment by sumbach** [comment]
I was able to replicate this issue in the ClojureScript codebase; bug report and proposed patch on [CLJS-1477](http://dev.clojure.org/jira/browse/CLJS-1477).

**Comment by sumbach** [comment]
This should be resolved in clojurescript-1.7.189:
- http://dev.clojure.org/jira/browse/CLJS-1477
- https://github.com/clojure/clojurescript/commit/39938634352f2e5ffe6cfd581dbaa9890d057b7f

**Comment by r0man** [comment]
@sumbach Thanks for looking into this!

**Comment by sumbach** [comment]
@r0man No problem. When I ran into similar warnings on my project, I was happy to find some validation that it wasn't project-specific. And as a bonus, I got a chance to dive into ClojureScript compiler internals :grinning:
