### ISSUE TITLE
Odd Nesting behaviour

### ISSUE THREAD

**Issue by afhammad** [r0man/sablono#43]
This `[:li "298" [:span "Things"]]`
outputs: `<li><span>298</span><span>Things</span></li>`

notice the number came out wrapped in a span.
 
While `[:li "298"]`
outputs: `<li>298</li>`

**Comment by Peeja** [comment]
I may be wrong, but I believe this is a React constraint: a DOM node can either have text content or element children, but not a mix of text nodes and element children.

**Comment by r0man** [comment]
Closing this, see @Peeja's comment

**Comment by afhammad** [comment]
Thanks
