### ISSUE TITLE
Please make sure Austin does not leak as dependency

### ISSUE THREAD

**Issue by martinklepsch** [r0man/sablono#51]
I don't exactly understand what the issue is but somehow Austin seems to get around the `:dev` profile and ends up in a lot of `pom.xml` files of Clojurescript projects. I don't know how to fix this so I'll leave it here for now. Will get back if/when I figure out what's going on.

**Comment by r0man** [comment]
@martinklepsch I removed austin and cut a new release ...

**Comment by martinklepsch** [comment]
@r0man thanks a lot! :100:
