### ISSUE TITLE
Using Sablono with React with Add-Ons

### ISSUE THREAD

**Issue by cigitia** [r0man/sablono#53]
As of Sablono 0.3.3 and [`cljsjs/react-with-addons`](https://github.com/cljsjs/packages/tree/master/react-with-addons) 0.12.2-4, if a clean ClojureScript project includes both `cljsjs/react-with-addons` and `sablono` in its dependencies and is then compiled in optimizations-none mode, then the compiler will use React without Add-Ons and not use React with Add-Ons, making [`React.addons`](http://facebook.github.io/react/docs/addons.html) completely unavailable in any of the project’s code.

Removing Sablono from the project’s dependencies, cleaning compiled files, and then recompiling causes React with Add-Ons to be used.

It should be possible to use React with Add-Ons along with Sablono in the same project, though I’m unsure whether this is at all possible with the compiler’s current behavior.

**Comment by r0man** [comment]
Can't you exclude cljsjs/react in your project? Like this:
`[sablono "0.3.3" :exclusions [cljsjs/react]]`

**Comment by the-kenny** [comment]
Yes, that's possible. But a nicer solution would be if Sablono uses ```scope "provided"``` just like for clojurescript.

**Comment by the-kenny** [comment]
Actually, nevermind. That doesn't work, as react-with-addons is a different artifact.

**Comment by cigitia** [comment]
Ah, sorry, I hadn’t realized that there was a compiler option to exclude dependencies from dependencies; this works. Thanks!
