### ISSUE TITLE
Cannot render cursors

### ISSUE THREAD

**Issue by gaverhae** [r0man/sablono#58]
I'm not sure whether this is a bug or out of scope, but it did surprise me: if a cursor points to a valid html vector, it looks like Sablono cannot render it. This was much less obvious in the original use-case, but here is a minimal example:

```clojure
(ns sablono-bug.core
  (:require [om.core :as om :include-macros true]
            [sablono.core :as html :refer-macros [html]]))

(def app-state
  (atom {:a [:pre "hello"]}))

(defn main []
  (om/root
   (fn [app owner]
     (reify
       om/IRender
       (render [_]
               (html
                [:div {}
                 [:pre (pr-str (:a app))]
                 [:div {} (:a app)]
                 [:div {} (into [] (:a app))]
                 [:div {} (:a @app-state)]]))))
   app-state
   {:target (. js/document (getElementById "app"))}))
```

I run that in a `chestnut` project, with Om 0.8.0-rc1 and Sablono 0.3.4. I can provide the full project if needed.

Expected output:

```
[:pre "hello"]
hello
hello
hello
```

Actual output:

```
[:pre "hello"]
25prepre211845686921537751054096hello16766851181961aa-21234075862153775105409625prepre211845686921537751054096hello167668511819616647951819618G__1G__1-21431073252154168321409616123663819664552961638615aa-212340758621537751054096167668511819621804244798192
hello
hello
```

**Comment by r0man** [comment]
@gaverhae Sablono does not ship with om as a dependency, so it doesn't know anything about how to render cursors. I think this can be solved by using `deref` on the cursor value, or you could try to extend the `IInterpret` protocol on om cursors.
https://github.com/r0man/sablono/blob/master/src/sablono/interpreter.cljx#L92
I hope, that helps.

**Comment by r0man** [comment]
Closing this now, you need to deref.
