### ISSUE TITLE
Om next compatibility

### ISSUE THREAD

**Issue by rhacker** [r0man/sablono#69]
I'm very new to the project, but I will use it in the upcoming project since Om next does provide some exciting features. I would love to know if sablono would work fine with Om next, if not, will it does ?

Thanks

**Comment by r0man** [comment]
Hey Dung,
the latest version should work fine with on.next. Do you experience any
problems?
Roman

**Comment by christoferjennings** [comment]
I'm trying out om.next with sablono and get `Warning: Each child in an array or iterator should have a unique "key" prop.` for every nested sablono element. I don't really know if I'm using either om.next or sablono _correctly_, though. :)

**Comment by r0man** [comment]
@christoferjennings I think you need to add a `:key` attribute to the children of `:select#distance` and `:select#direction`. Also take a look at `keyfn`:
https://github.com/omcljs/om/wiki/Documentation-%28om.next%29#factory

**Comment by christoferjennings** [comment]
Thanks @r0man 
I put a simplified project on github for reference... https://github.com/christoferjennings/om.next-sablono

Still need to dig deeper...

**Comment by christoferjennings** [comment]
OK. Got it. I wasn't reading it closely enough. The nested children are in for loops / iterators so they need :key ids. I was wrongly thinking it was _just_ nesting. .... definitely not a sablono issue!
thanks again @r0man !

**Comment by r0man** [comment]
Closing this ...
