### ISSUE TITLE
Should select boxes be wrapped with `wrap-form-element`?

### ISSUE THREAD

**Issue by caleb** [r0man/sablono#73]
Hi!

I noticed a bug in Om where `select` form elements would flash different values on Safari when a value was selected.

The solution was to wrap the select box with `wrap-form-element` like the `option`, `input` and `textarea`.

I know that Sablono used Om's code for making inputs behave (with the `wrap-form-element` function) so I thought I would post this here.

Here's the link to the Om issue (With a video example of the problem. A fix was created and merged in): [https://github.com/omcljs/om/issues/508](https://github.com/omcljs/om/issues/508)

What do you think?

**Comment by r0man** [comment]
@caleb Thanks, fixed and released `0.5.0`.
