### ISSUE TITLE
`html` macro exhibits odd behavior depending on syntactic nesting

### ISSUE THREAD

**Issue by Peeja** [r0man/sablono#80]
I'm not even sure how to best characterize the problem, except by example. Here's some Sablono code:

```clojure
(html
 [:div
  [:div {:class (list "foo" "bar")}]
  [:div {:class (vector "foo" "bar")}]

  (let []
    [:div {:class (list "foo" "bar")}])
  (let []
    [:div {:class (vector "foo" "bar")}])

  (when true
    [:div {:class (list "foo" "bar")}])
  (when true
    [:div {:class (vector "foo" "bar")}])

  (do
    [:div {:class (list "foo" "bar")}])
  (do
    [:div {:class (vector "foo" "bar")}])])
```

My expectation was that every `div` inside the outer one would have `class="foo bar"`. Instead, I got this:

```html
<div data-reactid=".c">
  <div class="(&quot;foo&quot; &quot;bar&quot;)" data-reactid=".c.0"></div>
  <div class="[&quot;foo&quot; &quot;bar&quot;]" data-reactid=".c.1"></div>
  <div class="foo,bar" data-reactid=".c.2"></div>
  <div class="foo bar" data-reactid=".c.3"></div>
  <div class="foo,bar" data-reactid=".c.4"></div>
  <div class="foo bar" data-reactid=".c.5"></div>
  <div class="(&quot;foo&quot; &quot;bar&quot;)" data-reactid=".f.6"></div>
  <div class="[&quot;foo&quot; &quot;bar&quot;]" data-reactid=".f.7"></div>
</div>
```

So, there are two things I see here:

1. In the middle 4 cases, I see that the values in a list are concatenated with a `","` delimiter, while the values in a vector use a `" "` delimiter. That looks like it might be a feature? It seems to me like the space is always more useful here, but maybe there's a reason for the distinction.

2. In the first and last 2 cases, things look very wrong. Whatever code is kindly concatenating values in the middle 4 cases doesn't kick in here. I'm a bit at a loss as to why.

**Comment by r0man** [comment]
@Peeja Should be fixed in master. Released as `0.5.2`.
