### ISSUE TITLE
Compilation error when using case statement

### ISSUE THREAD

**Issue by pangloss** [r0man/sablono#90]
Upgrading from 0.3.6 to 0.5.2, I ran into a couple of places that crashed with a case statement:

```clojure
(html [:div nil (case :a :a "a")])
```

The exception is 

```
Caused by: java.lang.IllegalArgumentException: Don't know how to create ISeq from: java.lang.Long
```

**Comment by r0man** [comment]
@pangloss Thanks for reporting, should be fixed in `0.5.3`.
